config/routes.rb
require 'sidekiq/web'

Weddingwall::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, ActiveAdmin::Devise.config
  
  authenticate :user do
    mount Sidekiq::Web, :at => "/sidekiq"
  end



  StaticController::Pages.each do |page|
    get page, :controller => 'static', :action => page
  end

  
  resources :rsvps, :only => [:show, :new, :create, :edit, :update]

  root :to => 'static#home'
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  belongs_to :rsvp

  validates_presence_of :email
  validates_format_of :email, :with => RFC822::EMAIL
  validates :attending, :inclusion => { :in => [true, false] }
  validates_presence_of :name

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  has_many :guests, :dependent => :destroy
  accepts_nested_attributes_for :guests
  validates_associated :guests

  before_create :assign_guid

  def assign_guid
    self.uuid = Guid.new.to_s
  end

  def to_param
    self.uuid
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  as_enum :role, :user => 1, :admin => 0
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
  helper :application

  protect_from_forgery
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  # GET /rsvps/1
  # GET /rsvps/1.xml
  def show
    @rsvp = Rsvp.includes(:guests).find_by_uuid!(params[:id])
    respond_with(@rsvp)
  end

  # GET /rsvps/new
  # GET /rsvps/new.xml
  def new
    @rsvp = Rsvp.new
    @rsvp.guests.build
    respond_with(@rsvp)
  end

  # POST /rsvps
  # POST /rsvps.xml
  def create
    @rsvp = Rsvp.new(rsvp_params)
    if @rsvp.save
      Notifications.delay.dispatch_rsvp(@rsvp)

      @rsvp.guests(true).each do |guest|
        Notifications.delay.confirm_rsvp(guest)
      end

    end
    respond_with(@rsvp)
  end

  # GET /rsvps/1/edit
  def edit
    @rsvp = Rsvp.includes(:guests).find_by_uuid!(params[:id])
    respond_with(@rsvp)
  end

  # PUT/PATCH /rsvps/1
  # PUT/PATCH /rsvps/1.xml
  def update
    @rsvp = Rsvp.find_by_uuid!(params[:id])
    @rsvp.update_attributes(rsvp_params)
    respond_with(@rsvp)
  end

  private

  def rsvp_params
    params.require(:rsvp).permit(:ip_address, :guests_attributes => [:attending, :diet, :email, :name]).merge(:ip_address => request.ip)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  StaticController::Pages = [:home, :events, :hotels]
  caches_page *StaticController::Pages
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_nav_data
    {
      'Photos' => root_path,
      'RSVP' => new_rsvp_path,
      'Events and Venues' => events_path,
      'Hotels' => hotels_path
    }
  end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = stylesheet_link_tag    "application", :media => "all"
    %link{:href => "http://fonts.googleapis.com/css?family=Playball", :rel => "stylesheet", :type => "text/css"}/
    = yield :head
    %title= content_for?(:title) ? yield(:title) : ENV['SITE_TITLE']
    = favicon_link_tag
    = csrf_meta_tags

  %body
    -# Header
    = render "shared/header"

    -# Mail Container
    .container.master-container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => name, :class => "alert alert-#{name}" if msg.is_a?(String)
      = yield

    = airbrake_javascript_notifier
    = jquery_include_tag :google
    = javascript_include_tag "application"
    /[if lt IE 9]
      = javascript_include_tag "lt_ie9"

    -# Footer
    = yield :footer

-# Google analytics
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '#{ENV['GOOGLE_ANALYTICS_ID']}']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/notifications.html.haml
%html
  %head
    %meta{'http-equiv' => 'Content-Type', 'content' => 'text/html; charset=UTF-8'}
    %title= content_for?(:title) ? yield(:title) : ENV['SITE_TITLE']

    -# The premailer-rails3 gem will take care of converting the stylesheet.
    = stylesheet_link_tag 'email'

  %body{'leftmargin' => 0, 'marginwidth' => 0, 'topmargin' => 0, 'marginheight' => 0, 'offset' => 0}
    .container
      .header= content_for?(:header) ? yield(:header) : ENV['DEFAULT_EMAIL_HEADER']
      .main= yield
      .footer= content_for?(:footer) ? yield(:footer) : ENV['DEFAULT_EMAIL_FOOTER']

app/views/layouts/notifications.text.erb
<%= yield %>

app/views/notifications/confirm_rsvp.html.haml
- content_for :header do
  %h2
    Your RSVP Submission on xjdecember.com

%p
  Here are the details of the your RSVP status:
  .well
    %p
      %strong
        Guest Name:
      = @guest.name
    %p
      %strong
        Guest Email:
      = @guest.email
    - if @guest.diet.present?
      %p
        %strong
          Dietary Restrictions:
        = @guest.diet
    %p
      %strong
        Attending?
      = (@guest.attending ? 'YES' : 'NO')

%p
  To change your submission details, use the following link:
  = link_to(edit_rsvp_path(@guest.rsvp, :only_path => false), edit_rsvp_path(@guest.rsvp, :only_path => false))

app/views/notifications/confirm_rsvp.text.erb
Your RSVP submission was created on xjdecember.com

Here are the details of your RSVP Status:

  Guest Name: <%= @guest.name %>
  Guest Email: <%= @guest.email %>
  Dietary Considerations: <%= @guest.diet %>
  Attending? <%= (@guest.attending ? 'YES' : 'NO') %>

To change your submission details, use the following link:
<%= edit_rsvp_path(@guest.rsvp, :only_path => false) %>

app/views/notifications/dispatch_rsvp.html.haml
- content_for :header do
  %h2
    New RSVP Submission on xjdecember.com

%p
  Here are the details of the new submission:
- @rsvp.guests.each_with_index do |guest, index|
  .well
    - if @rsvp.guests.length > 1
      %h3= "Guest #{index+1}:"
    %p
      %strong
        Guest Name:
      = guest.name
    %p
      %strong
        Guest Email:
      = guest.email
    - if guest.diet.present?
      %p
        %strong
          Dietary Restrictions:
        = guest.diet
    %p
      %strong
        Attending?
      = (guest.attending ? 'YES' : 'NO')

app/views/notifications/dispatch_rsvp.text.erb
A new RSVP submission was created on xjdecember.com

Here are the submission details:

<% @rsvp.guests.each_with_index do |guest, index| %>
  <%= '-' * 50 %>
  <% if @rsvp.guests.length > 1 %>
    Guest <%= index + 1 %>:
  <% end %>

  Guest Name: <%= guest.name %>
  Guest Email: <%= guest.email %>
  Dietary Considerations: <%= guest.diet %>
  Attending? <%= (guest.attending ? 'YES' : 'NO') %>

<% end %>

app/views/rsvps/_form.html.haml
= simple_form_for(@rsvp, :html => {:class => 'form-horizontal' }) do |f|
  = f.error_notification
  #guests
    = f.simple_fields_for :guests do |guest|
      = render 'guest_fields', :f => guest
    .links
      = link_to_add_association f, :guests, :class => 'btn btn-primary', :render_options => {:wrapper => 'bootstrap' } do
        %i.icon-plus
        Add Another Guest
  .form-actions
    .hidden
      = f.button :submit, "RSVP", :disable_with => 'Please wait ...'
    %a{:class => "btn btn-success", :data => {:role => :submit, :disable_with => "Saving..."}}
      %i.icon-glass
      Submit RSVP

- content_for :footer do
  :javascript
    $(function() {
      $('body').tooltip({
        selector: '[rel=tooltip]'
      });
    });

app/views/rsvps/_guest_fields.html.haml
.nested-fields.well
  = link_to_remove_association f, :class => "close" do
    %span{:title => "Click here to remove this guest.", :rel => :tooltip}
      &times;
  %h3 Guest Information
  = f.input :name
  = f.input :email
  = f.input :diet, :input_html => {:data => {:provide => :typeahead, :source => '["Gluten Free", "Vegetarian", "Vegan"]'}}
  = f.input :attending, :as => :radio_buttons, :item_wrapper_class => :inline, :default => true, :checked => true

app/views/rsvps/edit.html.haml
%h1.page-header
  Update your RSVP Submission

.row
  .span8
    = render 'form'

app/views/rsvps/index.html.haml
%h1 Listing rsvps
%table
  %tr
    %th Ip address
    %th
    %th
    %th
  - @rsvps.each do |rsvp|
    %tr
      %td= rsvp.ip_address
      %td= link_to 'Show', rsvp
      %td= link_to 'Edit', edit_rsvp_path(rsvp)
      %td= link_to 'Destroy', rsvp, confirm: 'Are you sure?', method: :delete
%br/
= link_to 'New Rsvp', new_rsvp_path

app/views/rsvps/new.html.haml
%h1.page-header
  RSVP Form
.row
  .span8
    = render 'form'

app/views/rsvps/show.html.haml
%h2
  RSVP Submission Details
%p
  Your RSVP submission has been saved. Here are the details you sent:
- @rsvp.guests.each_with_index do |guest, index|
  .well
    - if @rsvp.guests.length > 1
      %h3= "Guest #{index+1}:"
    %p
      %strong
        Guest Name:
      = guest.name
    %p
      %strong
        Guest Email:
      = guest.email
    - if guest.diet.present?
      %p
        %strong
          Dietary Restrictions:
        = guest.diet
    %p
      %strong
        Attending?
      = (guest.attending ? 'Yes' : 'No').upcase

app/views/shared/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.brand{href: root_path}
        Xavier &amp; Juliane
      %ul.nav
        - get_nav_data.each_pair do |key, val|
          %li{:class => (current_page?(val) ? :active : '')}= link_to key.to_s.gsub('_', ' '), val